-- Run this in InfinityFree phpMyAdmin to create all tables
-- Go to: Control Panel → phpMyAdmin → Select your database → SQL tab → paste this → Go

CREATE TABLE IF NOT EXISTS complaints (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  category VARCHAR(100) NOT NULL,
  location VARCHAR(255) NOT NULL,
  status VARCHAR(50) DEFAULT 'Submitted',
  priority VARCHAR(50) DEFAULT 'Medium',
  passphrase VARCHAR(100) NOT NULL,
  attachment VARCHAR(255),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  complaintId INT NOT NULL,
  message TEXT NOT NULL,
  adminName VARCHAR(255) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (complaintId) REFERENCES complaints(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  department VARCHAR(255) DEFAULT 'General',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Default admin password is: Admin@123
-- (bcrypt hash generated by the app on first startup)
-- Tables are created automatically when you run npm run dev
